{
 "title": "Services",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "version{job=\"Network\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Build",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "version{job=\"Network\"}",
     "legendFormat": "{{ build }}"
    }
   ]
  },
  {
   "title": "Blockchain alerts",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error-Messages",
   "type": "logs",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "{level=\"\u001b[31merror\u001b[39m\"}"
    }
   ]
  },
  {
   "title": "Build at",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "version{job=\"Network\"}"
    }
   ]
  },
  {
   "title": "Started at",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "startedInformation{job=\"Network\"}"
    }
   ]
  },
  {
   "title": "Blockchain size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "blockchainLength" }
   ]
  },
  {
   "title": "Blockchain increase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(blockchainLength[1h])" }
   ]
  },
  {
   "title": "Transaction Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(transactions[1h])", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(transactions)" }
   ]
  },
  {
   "title": "Consens",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Proposer",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{service=\"network\"} |~ \"is new proposer\""
    }
   ]
  },
  {
   "title": "Validator-Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(connections{type=\"validator\"}) + 1",
     "legendFormat": "current"
    },
    { "expr": "validator_min", "legendFormat": "min" },
    { "expr": "validator_max", "legendFormat": "max" },
    {
     "expr": "sum(connections{type=\"validator\"}) + 1 - avg(validator_min)",
     "legendFormat": "alert"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "connections{}" }
   ]
  },
  {
   "title": "Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}