version: "3.8"

volumes:
  health:

services:
  health:
    image: trustcerts/trustchain-health-check
    restart: ${RESTART-always}
    volumes:
      - health:/health
    environment:
      CONFIG_FOLDER: "/health"
      REPEAT: ${HEALTH_REPEAT}
      BC_ID: ${HEALTH_IDENTIFIER}
      BC_INVITE: ${HEALTH_SECRET}
      BC_NAME: ${HEALTH_NAME}
      BC_GATEWAY: ${HEALTH_GATEWAY}
      BC_OBSERVER: ${HEALTH_OBSERVER}
      BC_NETWORK: ${HEALTH_BC_ID}
